apiVersion: v2
name: loki
description: Meta-chart for Loki
type: application
version: 1.0.0

appVersion: 2.8.2
dependencies:
  - name: loki
    version: 5.5.0
    repository: https://grafana.github.io/helm-charts
