apiVersion: v2
name: argocd
description: Meta-chart for ArgoCD
type: application
version: 1.0.0

appVersion: 2.7.1
dependencies:
  - name: argo-cd
    version: 5.31.1
    repository: https://argoproj.github.io/argo-helm
