---
- include_vars: "{{ k3s_node_type | lower }}.yaml"
  tags:
    - k3s

- name: Check if k3s is installed
  ansible.builtin.command: which kubectl
  register: k3s_install
  changed_when: false
  failed_when: false # error = not found
  tags:
    - k3s

- include_tasks: shutdown.yaml
  when: k3s_install.rc == 0
  tags:
    - k3s
    - shutdown
