---
- import_tasks: files.yaml
  tags:
    - forward-proxy
    - files

- import_tasks: setup.yaml
  tags:
    - forward-proxy
    - setup

- include_tasks: ports.yaml
  when: socat_ports | length > 0
  tags:
    - forward-proxy
    - ports
