apiVersion: v2
name: cert-manager
description: Meta-chart for cert-manager
type: application
version: 1.0.1

appVersion: 1.12.2
dependencies:
  - name: cert-manager
    version: 1.12.2
    repository: https://charts.jetstack.io
